"""add book inventory transactions

Revision ID: 1a5b1cff7bae
Revises: ab7c61e7d045
Create Date: 2026-06-22 16:30:13.809024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5b1cff7bae'
down_revision = 'ab7c61e7d045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('acquisition', 'issue', 'return_', 'lost', 'damaged', 'decommission', name='changetype'), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_inventory_transactions')
    # ### end Alembic commands ###
