"""drop available_copies add cover_image_url

Revision ID: ab7c61e7d045
Revises: ef1932c7e5c9
Create Date: 2026-06-22 16:17:57.821993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7c61e7d045'
down_revision = 'ef1932c7e5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('available_copies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_copies', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
